DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS ticker_symbols;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE ticker_symbols (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ticker_symbol VARCHAR (10),
  company_name VARCHAR(255)
);